---
- hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - shell: echo 'Running PRE-TASKS ...'

    - name: Get hostname
      local_action: command hostname
      register: hostname

    - set_fact: 
        host: "{{ hostname.stdout }}"

  roles:
    - {role: ssh-banner, tags: ['ssh-banner', 'banner', 'bootstrap', 'provision']}
    #- {role: minikube, tags: ['minikube', 'kubernetes', 'kubectl', 'cluster']}
    # - {role: common, tags: ['common', 'all']}

  tasks:
    - shell: echo 'Running TASKS ...' "{{ host }}"

  post_tasks:
    - shell: echo 'Running POST-TASKS ...'
