---
- hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - shell: echo 'Running PRE-TASKS ...'

    - name: Get hostname
      local_action: command hostname
      register: hostname

    - debug: msg=hostname.stdout

  roles:
    - {role: ssh-banner, host: 'My Machine' ,tags: ['ssh-banner', 'banner', 'bootstrap', 'provision']}
    # - {role: common, tags: ['common', 'all']}

  tasks:
    - shell: echo 'Running TASKS ...'

  post_tasks:
    - shell: echo 'Running POST-TASKS ...'
