---
- hosts: localhost
  connection: local
  become: true
  gather_facts: False
  tasks:
    - name: https://github.com/ansible/ansible/issues/22455
      git:
        repo: https://github.com/minetest-technic/technic
        dest: /var/games/minetest-server/.minetest/mods/technic
        remote: origin
        update: yes
      register: status
