---

- name: Install terraform
  become: true 
  unarchive:
    src: "{{ tf_url }}"
    dest: /usr/local/bin
    remote_src: yes
    owner: ansible

- name: check installed terraform version
  command: terraform version
  register: tf_installed_version

- fail:
  when: 'tf_version_2 | string not in tf_installed_version.stdout'
