---
#general purpose playbook to be applied on all platforms
- name: Create temp directory for work
  command: mktemp -d
  changed_when: false
  register: temp_dir

- name: Download get-pip.py
  become: true
  get_url: 
    url: "{{ pip_url }}"
    dest: /tmp
    owner: root

- name: Install pip
  become: true
  shell: python get-pip.py
  args:
    chdir: /tmp

# - name: Copy requirements.txt
- name: Install pip packages
  become: true
  command: pip install -r files/ansible_requirements.txt
  register: status

# - name: Copy
- name: Install pip packages
  command: pip install -r files/ansible_requirements.txt
  register: status

# - name: Clone dotfiles repo
- name: Clone dotfiles repo
  git:
    repo: git@github.com:Miyurz/dotfiles.git
    dest: "{{ temp_dir }}"
    refspec: 'refs/heads/master'
