---

- include: debian.yml
  when: ansible_os_family == 'Debian'
  tags: package

- include: redhat.yml
  when: ansible_os_family == 'RedHat'
  tags: package

- include: darwin.yml
  when: ansible_os_family == 'Darwin'
  tags: package

#general purpose playbook to be applied on all platforms
- name: Create temp directory for work
  command: mktemp -d
  changed_when: false
  register: temp_dir

- name: Download get-pip.py
  become: true
  get_url: 
    url: "{{ pip_url }}"
    dest: /tmp
    owner: root

- name: Install pip
  become: true
  shell: python get-pip.py
  args:
    chdir: /tmp

# - name: Copy requirements.txt
- name: Install pip packages
  become: true
  pip:
    requirements: ansible_requirements.txt
    state: present
    chdir: files/

# - name: Clone dotfiles repo
- name: Clone dotfiles repo
  git:
    repo: git@github.com:Miyurz/dotfiles.git
    dest: "{{ temp_dir }}"
    refspec: 'master'
